---
services:
  db:
    image: mydockerhubbs/repo1:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: mydockerhubbs/repo1:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db
  book_service:
    image: mydockerhubbs/repo1:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    depends_on:
      - db
  borrow_service:
    image: mydockerhubbs/repo1:borrowimage
    ports:
      - "5004:5004"
    deploy:
      replicas: 1
    depends_on:
      - db
  app_service:
    image: mydockerhubbs/repo1:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    depends_on:
      - auth_service
      - book_service
      - order_service
